services:
  ollama-server:
    image: ollama/ollama:latest
    container_name: toxicity_ollama
    volumes:
      - ./ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

  streamlit-app:
    build: .
    container_name: toxicity_gui
    depends_on:
      - ollama-server
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://ollama-server:11434
    volumes:
      - ./app.py:/app/app.py
      - ./hf_cache:/root/.cache/huggingface
    restart: unless-stopped